#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean, stdev


ROOT = Path(__file__).resolve().parents[1]


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_rows(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def numeric(row: dict, key: str) -> float | None:
    value = row.get(key)
    return None if value in (None, "", "None", "nan") else float(value)


def summarise(rows: list[dict]) -> list[dict]:
    grouped = defaultdict(list)
    for row in rows:
        grouped[(row["method"], row["attack_type"])].append(row)
    summary = []
    for (method, attack_type), group in sorted(grouped.items()):
        record = {
            "method": method,
            "attack_type": attack_type,
            "target_runs": len(group),
        }
        for metric in (
            "accuracy",
            "mse",
            "ssim",
            "psnr",
            "lpips",
            "identity_top1_success",
        ):
            values = [value for row in group if (value := numeric(row, metric)) is not None]
            record[f"{metric}_mean"] = mean(values) if values else None
            record[f"{metric}_std"] = stdev(values) if len(values) > 1 else None
        summary.append(record)
    return summary


def latex_value(record: dict, metric: str) -> str:
    average = record.get(f"{metric}_mean")
    deviation = record.get(f"{metric}_std")
    if average is None:
        return "--"
    if deviation is None:
        return f"{average:.4f}"
    return f"{average:.4f} $\\pm$ {deviation:.4f}"


def write_latex_table(summary: list[dict], path: Path) -> None:
    lines = [
        "% Generated by scripts/generate_paper_assets.py; do not edit manually.",
        "\\begin{tabular}{llrrrr}",
        "\\toprule",
        "Method & Attack & Accuracy & MSE & LPIPS & Identity Top-1 \\\\",
        "\\midrule",
    ]
    for record in summary:
        method = record["method"].replace("_", "\\_")
        attack = record["attack_type"].replace("_", "\\_")
        lines.append(
            f"{method} & {attack} & {latex_value(record, 'accuracy')} & "
            f"{latex_value(record, 'mse')} & {latex_value(record, 'lpips')} & "
            f"{latex_value(record, 'identity_top1_success')} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_privacy_utility_plot(summary: list[dict], path: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    selected = [row for row in summary if row["attack_type"] == "conv_decoder"]
    figure, axis = plt.subplots(figsize=(6.6, 4.2))
    for row in selected:
        if row["mse_mean"] is None:
            continue
        axis.scatter(row["accuracy_mean"], row["mse_mean"], s=42)
        axis.annotate(
            row["method"],
            (row["accuracy_mean"], row["mse_mean"]),
            xytext=(4, 4),
            textcoords="offset points",
            fontsize=7,
        )
    axis.set_xlabel("Target-test classification accuracy")
    axis.set_ylabel("Reconstruction MSE (higher is more private)")
    axis.grid(True, alpha=0.25)
    figure.tight_layout()
    figure.savefig(path, bbox_inches="tight")
    plt.close(figure)


def read_jsonl(path: Path) -> list[dict]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def summarise_efficiency(rows: list[dict]) -> tuple[list[dict], list[Path]]:
    unique_runs = {}
    for row in rows:
        unique_runs[(row["method"], row["run_dir"])] = row
    grouped = defaultdict(list)
    provenance_paths = []
    for (method, run_dir_text), _ in sorted(unique_runs.items()):
        run_dir = Path(run_dir_text)
        if not run_dir.is_absolute():
            run_dir = ROOT / run_dir
        training_path = run_dir / "training.jsonl"
        profile_path = run_dir / "efficiency_profile.json"
        calibration_path = run_dir / "channel_calibration.json"
        if not training_path.is_file() and calibration_path.is_file():
            calibration = json.loads(calibration_path.read_text(encoding="utf-8"))
            source_checkpoint = Path(calibration["source_checkpoint"])
            if not source_checkpoint.is_absolute():
                source_checkpoint = ROOT / source_checkpoint
            training_path = source_checkpoint.parent / "training.jsonl"
            provenance_paths.append(calibration_path)
        if not training_path.is_file() or not profile_path.is_file():
            raise FileNotFoundError(
                f"efficiency evidence is incomplete for {run_dir_text}"
            )
        training = read_jsonl(training_path)
        profile = json.loads(profile_path.read_text(encoding="utf-8"))
        if not training:
            raise ValueError(f"training log is empty for {run_dir_text}")
        grouped[method].append(
            {
                "total_epoch_seconds": mean(
                    float(record["total_epoch_seconds"]) for record in training
                ),
                "statistics_refresh_seconds": mean(
                    float(record["statistics_refresh_seconds"])
                    for record in training
                ),
                "peak_gpu_memory_bytes": max(
                    int(record["peak_gpu_memory_bytes"]) for record in training
                ),
                "edge_latency_ms": float(
                    profile["edge_latency_ms_per_sample_mean"]
                ),
                "transmitted_bytes": int(
                    profile["transmitted_bytes_per_sample_fp32"]
                ),
            }
        )
        provenance_paths.extend((training_path, profile_path))
    summary = []
    for method, records in sorted(grouped.items()):
        summary.append(
            {
                "method": method,
                "target_runs": len(records),
                "total_epoch_seconds_mean": mean(
                    row["total_epoch_seconds"] for row in records
                ),
                "statistics_refresh_seconds_mean": mean(
                    row["statistics_refresh_seconds"] for row in records
                ),
                "peak_gpu_memory_gib_mean": mean(
                    row["peak_gpu_memory_bytes"] / (1024**3) for row in records
                ),
                "edge_latency_ms_mean": mean(
                    row["edge_latency_ms"] for row in records
                ),
                "transmitted_kib": mean(
                    row["transmitted_bytes"] / 1024 for row in records
                ),
            }
        )
    return summary, provenance_paths


def write_efficiency_table(summary: list[dict], path: Path) -> None:
    lines = [
        "% Generated by scripts/generate_paper_assets.py; do not edit manually.",
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "Method & Epoch (s) & Refresh (s) & Peak GiB & Edge (ms) & Tx KiB \\\\",
        "\\midrule",
    ]
    for row in summary:
        method = row["method"].replace("_", "\\_")
        lines.append(
            f"{method} & {row['total_epoch_seconds_mean']:.2f} & "
            f"{row['statistics_refresh_seconds_mean']:.2f} & "
            f"{row['peak_gpu_memory_gib_mean']:.2f} & "
            f"{row['edge_latency_ms_mean']:.3f} & "
            f"{row['transmitted_kib']:.1f} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target-level-csv", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    rows = read_rows(args.target_level_csv)
    if not rows:
        raise ValueError("target-level aggregate is empty")
    summary = summarise(rows)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    table_path = args.output_dir / "results_table.tex"
    efficiency_path = args.output_dir / "efficiency_table.tex"
    plot_path = args.output_dir / "privacy_utility.pdf"
    write_latex_table(summary, table_path)
    write_privacy_utility_plot(summary, plot_path)
    efficiency, efficiency_inputs = summarise_efficiency(rows)
    write_efficiency_table(efficiency, efficiency_path)
    provenance = {
        "schema_version": 1,
        "input": str(args.target_level_csv),
        "input_sha256": file_sha256(args.target_level_csv),
        "target_rows": len(rows),
        "summary_groups": len(summary),
        "outputs": {
            table_path.name: file_sha256(table_path),
            efficiency_path.name: file_sha256(efficiency_path),
            plot_path.name: file_sha256(plot_path),
        },
        "efficiency_inputs": {
            str(path.relative_to(ROOT)): file_sha256(path)
            for path in efficiency_inputs
        },
    }
    (args.output_dir / "provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True), encoding="utf-8"
    )
    print(json.dumps(provenance, sort_keys=True))


if __name__ == "__main__":
    main()
