#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean, stdev


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def latex_name(value: str) -> str:
    return value.replace("_", "\\_")


def generalisation_table(rows: list[dict], output: Path) -> None:
    grouped = defaultdict(list)
    for row in rows:
        run_parts = Path(row["run_dir"]).parts
        marker = run_parts.index("generalisation")
        variant = run_parts[marker + 1]
        grouped[(variant, row["method"], row["attack_type"])].append(row)
    lines = [
        "% Generated by scripts/generate_uacem_supplementary_assets.py.",
        "\\begin{tabular}{lllrr}",
        "\\toprule",
        "Setting & Method & Attack & Accuracy & MSE \\\\",
        "\\midrule",
    ]
    for (variant, method, attack), group in sorted(grouped.items()):
        accuracies = [float(row["accuracy"]) for row in group]
        mses = [float(row["mse"]) for row in group]
        lines.append(
            f"{latex_name(variant)} & {latex_name(method)} & {latex_name(attack)} & "
            f"{mean(accuracies):.4f} $\\pm$ {stdev(accuracies):.4f} & "
            f"{mean(mses):.5f} $\\pm$ {stdev(mses):.5f} \\\\" 
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ablation_table(payload: dict, output: Path) -> None:
    lines = [
        "% Generated by scripts/generate_uacem_supplementary_assets.py.",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Variant & Alpha & Validation accuracy & Auxiliary MSE \\\\",
        "\\midrule",
    ]
    for row in payload["variants"]:
        lines.append(
            f"{latex_name(row['variant'])} & {row['alpha']:.2f} & "
            f"{row['validation_accuracy']:.4f} & "
            f"{row['attacker_validation_mse_mean']:.5f} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def allocation_plot(calibration_paths: list[Path], output: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    values = [
        json.loads(path.read_text(encoding="utf-8"))["channel_multipliers"]
        for path in calibration_paths
    ]
    channels = range(len(values[0]))
    averages = [mean(run[index] for run in values) for index in channels]
    deviations = [stdev(run[index] for run in values) for index in channels]
    figure, axis = plt.subplots(figsize=(7.0, 3.8))
    axis.errorbar(channels, averages, yerr=deviations, marker="o", capsize=3)
    axis.axhline(1.0, color="black", linewidth=1, linestyle="--")
    axis.set_xlabel("Smashed-feature channel")
    axis.set_ylabel("Noise standard-deviation multiplier")
    axis.set_xticks(list(channels))
    axis.grid(True, alpha=0.25)
    figure.tight_layout()
    figure.savefig(output, bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--generalisation-csv", required=True, type=Path)
    parser.add_argument("--ablation-json", required=True, type=Path)
    parser.add_argument("--main-results-root", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    generalisation_table(
        read_csv(args.generalisation_csv),
        args.output_dir / "generalisation_table.tex",
    )
    ablation_table(
        json.loads(args.ablation_json.read_text(encoding="utf-8")),
        args.output_dir / "ablation_table.tex",
    )
    calibration_paths = sorted(
        args.main_results_root.glob("seed12[5-9]_uacem/channel_calibration.json")
    )
    if len(calibration_paths) != 5:
        raise ValueError("channel-allocation plot requires five main target seeds")
    allocation_plot(calibration_paths, args.output_dir / "channel_allocation.pdf")
    print(json.dumps({"output_dir": str(args.output_dir), "assets": 3}))


if __name__ == "__main__":
    main()
